name: Tests


on:
 push:
   branches:
     - main
     - dev
     - master

jobs:
  hello-world:
    runs-on:  ubuntu-20.04

    steps:
     - name: Say hello world
       run: echo Welcome to the GitHub Actions workshop !