name: Tests


on:
 push:
   branches:
     - main
     - dev
     - master

jobs:
  hello-world:
    runs-on:  ubuntu-20.04

    steps:
     - name: Say hello world
       shell: bash
       run: echo Welcome to the GitHub Actions workshop !
  unit-test:
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        shell: bash
        run: make tests_run

      - name: Get Coverage
        if: ${{ always() }}
        shell: bash
        run: make coverage > coverage_outputs

      - name: Upload coverage artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage_outputs
          path: ./coverage_outputs